name: build
on: [push]

jobs:
  build:

    name: ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Boost
        run: sudo apt-get install libboost-all-dev

      - name: Install Curl
        run: sudo apt-get install libcurl-dev

      - name: Install GTest
        run: sudo apt-get install libgtest-dev -y

      - name: Install Clang-tidy
        run: sudo apt-get install -y clang-tidy

      - name: Install Scan-build
        run: sudo apt-get install -y clang-tools

      - name: Install cppcheck
        run: sudo apt update && sudo apt install cppcheck

      - name: Install Cpplint
        run: sudo apt-get install python3-pip && pip install --user cpplint

      - name: install fbinfer
        run: VERSION=1.1.0; curl -sSL "https://github.com/facebook/infer/releases/download/v$VERSION/infer-linux64-v$VERSION.tar.xz" | sudo tar -C /opt -xJ && sudo ln -s "/opt/infer-linux64-v$VERSION/bin/infer" /usr/local/bin/infer

      - name: Valgrind install
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: scan-build  clang-tidy
        run: cd project && mkdir build && cd build && scan-build cmake .. && scan-build make && cd ..

      - name: cppcheck
        run: cppcheck web/src web/tests  --enable=all --error-exitcode=1 -I web/include --suppress=missingIncludeSystem

      - name: Cpplint
        run: cpplint --extensions=cpp,h --filter=-runtime/references,-legal/copyright,-build/include_subdir,-whitespace/line_length,-readability/casting web/src/* web/include/* && cpplint --extensions=cpp --filter=-runtime/references,-legal/copyright,-build/include_subdir,-whitespace/line_length,-readability/casting tests/*

