name: build
on: [push]

jobs:
  build:

    name: ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Install Clang-tidy
        run: sudo apt-get install -y clang-tidy

      - name: Install Scan-build  
        run: sudo apt-get install -y clang-tools

      - name: Install cppcheck
        run: sudo apt update && sudo apt install cppcheck
 
      - name: Install Cpplint
        run: sudo apt-get install python3-pip && pip install --user cpplint

      - name: cppcheck
        run: cppcheck ./lib/*  --enable=all --error-exitcode=1 -I ./lib/* --suppress=missingIncludeSystem
        
      - name: Cpplint
        run: cpplint --extensions=cpp,h --filter=-runtime/references,-legal/copyright,-build/include_subdir,-whitespace/line_length,-readability/casting ./lib/* && cpplint --extensions=cpp --filter=-runtime/references,-legal/copyright,-build/include_subdir,-whitespace/line_length,-readability/casting tests/*
