name: build
on: [push]

jobs:
  build:

    name: ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install GTest
        run: sudo apt-get install libgtest-dev -y 
        
      - name: Install Clang-tidy
        run: sudo apt-get install -y clang-tidy

      - name: Install Scan-build  
        run: sudo apt-get install -y clang-tools
        
      - name: scan-build api
        run: cd ./project/api/ && bash st.bash

      - name: scan-build web
        run: cd ./project/web/ && bash st.bash
        
      - name: scan-build qt
        run: cd ./project/qt/lib && bash st.bash    
        